### ISSUE TITLE
Issues setting up the sample

### ISSUE THREAD

**Issue by anjovanov** [rzo1/crawler4j-postgres-sample#1]
I really feel like I'm annoying, the professor at uni gave me this task and I don't have java or database knowledge whatsoever. Thank you so much for writing the whole sample I'm sure it would help a lot of people. However, I ran into some problems.

In the SampleLauncher class I got a problem at this line of code:

`controller.start(new PostgresCrawlerFactory("jdbc:postgresql://localhost:1337/postgres","postgres","12345"), numberOfCrawlers);`
It says: The method start in the type CrawlerController is not applicable for the arguments.

Also got problems in the PostgresCrawlerFactory class:

`public class PostgresCrawlerFactory implements CrawlController.WebCrawlerFactory<PostgresWebCrawler>`
It says: CrawlController.WebCrawlerFactory cannot be resolved to a type.

I think it has something to do with the type CrawlerController

Besides that everything seems fine.
Thank you for your time

**Comment by rzo1** [comment]
Did you just clone the example from this repository? Do you have a working local Maven installation? 

And more important: Did you change the version of `crawler4j` from `4.2` to something else? WebCrawlerFactory (and related methods) were introduced in ´4.2´.

**Comment by anjovanov** [comment]
Alright, I was using crawler4j, with 4.1-dependacies. So I downloaded maven, and imported your project and the project build successfully, but I keep getting:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Slf4j dependacy is installed, but I keep getting this

**Comment by rzo1** [comment]
Seems, that you did not put in the necessary libraries or your classpath seems to be malformed... do you provide  appropriate `log4j.xml` configuration file?

```
      <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>${slf4j.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>${log4j.version}</version>
            <scope>runtime</scope>
        </dependency>
```

**Comment by anjovanov** [comment]
Yes that was already in pom.xml

And this is in log4j.xml

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM
        "http://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/xml/doc-files/log4j.dtd">

<log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">

    <appender name="CONSOLE" class="org.apache.log4j.ConsoleAppender">
        <layout class="org.apache.log4j.PatternLayout">
            <param name="ConversionPattern"
                   value="%d{ISO8601} %-5p [%t] %c{1} (%L): %m%n"/>
        </layout>
    </appender>

    <logger name="com.github.rzo1">
        <level value="INFO"/>
    </logger>

    <logger name="com.mchange">
        <level value="WARN"/>
    </logger>

    <logger name="org.apache.http.client.protocol">
        <level value="ERROR"/>
    </logger>

    <root>
        <level value="WARN"/>
        <appender-ref ref="CONSOLE"/>
    </root>

</log4j:configuration>

```

**Comment by rzo1** [comment]
This is a local configuration problem. Check [this](http://www.slf4j.org/codes.html#StaticLoggerBinder):

> This warning message is reported when the org.slf4j.impl.StaticLoggerBinder class could not be loaded into memory. This happens when no appropriate SLF4J binding could be found on the class path. Placing one (and only one) of slf4j-nop.jar, slf4j-simple.jar, slf4j-log4j12.jar, slf4j-jdk14.jar or logback-classic.jar on the class path should solve the problem.
