### ISSUE TITLE
Do you support multi account login to crawl data? 

### ISSUE THREAD

**Issue by chunfytseng** [rzo1/crawler4j-postgres-sample#2]
Do you support multi account login to crawl data? Do you support multi account login to crawl data? I want to use a crawler to implement an interface function to support multiple account login crawling data, different accounts do not interfere with each other. After crawling the data, the crawler does not stop waiting for the new task.

**Comment by rzo1** [comment]
You should ask in the crawler-repository: https://github.com/yasserg/crawler4j
